meta_product_name: "Find Mike"
meta_title: "Find Mike - Find your next gig in the spotlight "
meta_description: "Find Mike allows amateur comedians or have a go heros to find venues to perform. Will you find Mike for your next gig? "
meta_image: "find-mike-share-image.png" # should exist in `app/assets/images/`
